openapi: 3.0.0
info:
  title: Medichain API
  version: 1.0.0
  description: |
    Medichain API includes:
    - Authentication (JWT)
    - User document (certificate) management

  contact:
    name: Dmytro Kupets
    email: dev@medichain.app

  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

x-logo:
  url: https://avatars.githubusercontent.com/u/103669226?s=200
  altText: Medichain Logo

tags:
  - name: Auth
    description: Authentication-related endpoints
  - name: Documents
    description: Ендпоінти, пов’язані з цифровими документами

paths:
  /api/v1/auth/register:
    post:
      tags:
        - Auth
      summary: Register
      description: Creates a new user using phone and password. Returns access and refresh tokens.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, password]
              properties:
                phone:
                  type: string
                  example: "+380991234567"
                password:
                  type: string
                  example: StrongPassword123
      responses:
        '201':
          description: User successfully registered
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: User already exists
        '500':
          description: Server error

  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Log in an existing user
      description: Authenticates a user and returns new access and refresh tokens.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [phone, password]
              properties:
                phone:
                  type: string
                  example: "+380991234567"
                password:
                  type: string
                  example: StrongPassword123
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid password
        '404':
          description: User not found
        '500':
          description: Server error

  /api/v1/auth/refresh-token:
    post:
      tags:
        - Auth
      summary: Refresh tokens
      description: Issues new access and refresh tokens using a valid refresh token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [refreshToken]
              properties:
                refreshToken:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5...
      responses:
        '200':
          description: Tokens refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Refresh token missing
        '403':
          description: Invalid or expired refresh token

  /api/v1/auth/logout:
    post:
      tags:
        - Auth
      summary: Log out user
      description: Logs out the user by invalidating the refresh token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [refreshToken]
              properties:
                refreshToken:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5...
      responses:
        '200':
          description: Logged out successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out
        '500':
          description: Server error

  /api/v1/documents:
    post:
      tags:
        - Documents
      summary: Створення нового документа
      description: Додає новий цифровий документ для користувача.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentCreateRequest'
      responses:
        '201':
          description: Документ успішно створено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
        '400':
          description: Помилка валідації або відсутні поля
        '500':
          description: Внутрішня помилка сервера

    get:
      tags:
        - Documents
      summary: Отримання списку документів
      description: Повертає список документів з можливістю фільтрації за типом і userId, та з пагінацією.
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 1
          description: Номер сторінки
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
          description: Кількість елементів на сторінці
        - in: query
          name: type
          schema:
            type: string
          description: Тип документа (наприклад passport, driver_license)
        - in: query
          name: userId
          schema:
            type: string
            format: uuid
          description: ID користувача
      responses:
        '200':
          description: Успішне отримання списку
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DocumentResponse'
                  pagination:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      limit:
                        type: integer
                      totalPages:
                        type: integer
        '500':
          description: Внутрішня помилка сервера

components:
  schemas:
    AuthResponse:
      type: object
      properties:
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        refreshToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
        accessExpiresIn:
          type: integer
          example: 900
        accessExpiresAt:
          type: string
          format: date-time
          example: "2025-04-07T13:45:10.000Z"
        refreshExpiresIn:
          type: integer
          example: 604800
        refreshExpiresAt:
          type: string
          format: date-time
          example: "2025-04-14T13:45:10.000Z"

    DocumentCreateRequest:
      type: object
      required:
        - title
        - type
        - userId
      properties:
        title:
          type: string
          example: Паспорт громадянина України
        description:
          type: string
          example: Біометричний паспорт
        imageUrl:
          type: string
          example: https://example.com/documents/passport.jpg
        issueDate:
          type: string
          format: date
          example: "2020-01-01"
        expiryDate:
          type: string
          format: date
          example: "2030-01-01"
        type:
          type: string
          example: passport
        userId:
          type: string
          format: uuid
          example: 550e8400-e29b-41d4-a716-446655440000

    DocumentResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        imageUrl:
          type: string
        issueDate:
          type: string
          format: date
        expiryDate:
          type: string
          format: date
        type:
          type: string
        status:
          type: string
        userId:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
